/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppTeamRouteImport } from './routes/_authenticated/app.team'
import { Route as AuthenticatedAppSupportRouteImport } from './routes/_authenticated/app.support'
import { Route as AuthenticatedAppSuppliersRouteImport } from './routes/_authenticated/app.suppliers'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppRemindersRouteImport } from './routes/_authenticated/app.reminders'
import { Route as AuthenticatedAppProductsRouteImport } from './routes/_authenticated/app.products'
import { Route as AuthenticatedAppPosRouteImport } from './routes/_authenticated/app.pos'
import { Route as AuthenticatedAppPayablesRouteImport } from './routes/_authenticated/app.payables'
import { Route as AuthenticatedAppInvoicesRouteImport } from './routes/_authenticated/app.invoices'
import { Route as AuthenticatedAppEmployeesRouteImport } from './routes/_authenticated/app.employees'
import { Route as AuthenticatedAppDebtorsRouteImport } from './routes/_authenticated/app.debtors'
import { Route as AuthenticatedAppCustomersRouteImport } from './routes/_authenticated/app.customers'
import { Route as AuthenticatedAppChangelogRouteImport } from './routes/_authenticated/app.changelog'
import { Route as AuthenticatedAppAssistRouteImport } from './routes/_authenticated/app.assist'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AuthenticatedAppPlatformTicketsRouteImport } from './routes/_authenticated/app.platform.tickets'
import { Route as AuthenticatedAppPlatformReleasesRouteImport } from './routes/_authenticated/app.platform.releases'
import { Route as AuthenticatedAppPlatformErrorsRouteImport } from './routes/_authenticated/app.platform.errors'
import { Route as AuthenticatedAppPlatformCompaniesRouteImport } from './routes/_authenticated/app.platform.companies'
import { Route as AuthenticatedAppPlatformAdminsRouteImport } from './routes/_authenticated/app.platform.admins'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTeamRoute = AuthenticatedAppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSupportRoute = AuthenticatedAppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSuppliersRoute =
  AuthenticatedAppSuppliersRouteImport.update({
    id: '/suppliers',
    path: '/suppliers',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppRemindersRoute =
  AuthenticatedAppRemindersRouteImport.update({
    id: '/reminders',
    path: '/reminders',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProductsRoute =
  AuthenticatedAppProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPosRoute = AuthenticatedAppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPayablesRoute =
  AuthenticatedAppPayablesRouteImport.update({
    id: '/payables',
    path: '/payables',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppInvoicesRoute =
  AuthenticatedAppInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppEmployeesRoute =
  AuthenticatedAppEmployeesRouteImport.update({
    id: '/employees',
    path: '/employees',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDebtorsRoute = AuthenticatedAppDebtorsRouteImport.update({
  id: '/debtors',
  path: '/debtors',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppCustomersRoute =
  AuthenticatedAppCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppChangelogRoute =
  AuthenticatedAppChangelogRouteImport.update({
    id: '/changelog',
    path: '/changelog',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAssistRoute = AuthenticatedAppAssistRouteImport.update({
  id: '/assist',
  path: '/assist',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppPlatformTicketsRoute =
  AuthenticatedAppPlatformTicketsRouteImport.update({
    id: '/platform/tickets',
    path: '/platform/tickets',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPlatformReleasesRoute =
  AuthenticatedAppPlatformReleasesRouteImport.update({
    id: '/platform/releases',
    path: '/platform/releases',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPlatformErrorsRoute =
  AuthenticatedAppPlatformErrorsRouteImport.update({
    id: '/platform/errors',
    path: '/platform/errors',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPlatformCompaniesRoute =
  AuthenticatedAppPlatformCompaniesRouteImport.update({
    id: '/platform/companies',
    path: '/platform/companies',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPlatformAdminsRoute =
  AuthenticatedAppPlatformAdminsRouteImport.update({
    id: '/platform/admins',
    path: '/platform/admins',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/assist': typeof AuthenticatedAppAssistRoute
  '/app/changelog': typeof AuthenticatedAppChangelogRoute
  '/app/customers': typeof AuthenticatedAppCustomersRoute
  '/app/debtors': typeof AuthenticatedAppDebtorsRoute
  '/app/employees': typeof AuthenticatedAppEmployeesRoute
  '/app/invoices': typeof AuthenticatedAppInvoicesRoute
  '/app/payables': typeof AuthenticatedAppPayablesRoute
  '/app/pos': typeof AuthenticatedAppPosRoute
  '/app/products': typeof AuthenticatedAppProductsRoute
  '/app/reminders': typeof AuthenticatedAppRemindersRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/suppliers': typeof AuthenticatedAppSuppliersRoute
  '/app/support': typeof AuthenticatedAppSupportRoute
  '/app/team': typeof AuthenticatedAppTeamRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/platform/admins': typeof AuthenticatedAppPlatformAdminsRoute
  '/app/platform/companies': typeof AuthenticatedAppPlatformCompaniesRoute
  '/app/platform/errors': typeof AuthenticatedAppPlatformErrorsRoute
  '/app/platform/releases': typeof AuthenticatedAppPlatformReleasesRoute
  '/app/platform/tickets': typeof AuthenticatedAppPlatformTicketsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/assist': typeof AuthenticatedAppAssistRoute
  '/app/changelog': typeof AuthenticatedAppChangelogRoute
  '/app/customers': typeof AuthenticatedAppCustomersRoute
  '/app/debtors': typeof AuthenticatedAppDebtorsRoute
  '/app/employees': typeof AuthenticatedAppEmployeesRoute
  '/app/invoices': typeof AuthenticatedAppInvoicesRoute
  '/app/payables': typeof AuthenticatedAppPayablesRoute
  '/app/pos': typeof AuthenticatedAppPosRoute
  '/app/products': typeof AuthenticatedAppProductsRoute
  '/app/reminders': typeof AuthenticatedAppRemindersRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/suppliers': typeof AuthenticatedAppSuppliersRoute
  '/app/support': typeof AuthenticatedAppSupportRoute
  '/app/team': typeof AuthenticatedAppTeamRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/platform/admins': typeof AuthenticatedAppPlatformAdminsRoute
  '/app/platform/companies': typeof AuthenticatedAppPlatformCompaniesRoute
  '/app/platform/errors': typeof AuthenticatedAppPlatformErrorsRoute
  '/app/platform/releases': typeof AuthenticatedAppPlatformReleasesRoute
  '/app/platform/tickets': typeof AuthenticatedAppPlatformTicketsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/app/assist': typeof AuthenticatedAppAssistRoute
  '/_authenticated/app/changelog': typeof AuthenticatedAppChangelogRoute
  '/_authenticated/app/customers': typeof AuthenticatedAppCustomersRoute
  '/_authenticated/app/debtors': typeof AuthenticatedAppDebtorsRoute
  '/_authenticated/app/employees': typeof AuthenticatedAppEmployeesRoute
  '/_authenticated/app/invoices': typeof AuthenticatedAppInvoicesRoute
  '/_authenticated/app/payables': typeof AuthenticatedAppPayablesRoute
  '/_authenticated/app/pos': typeof AuthenticatedAppPosRoute
  '/_authenticated/app/products': typeof AuthenticatedAppProductsRoute
  '/_authenticated/app/reminders': typeof AuthenticatedAppRemindersRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/suppliers': typeof AuthenticatedAppSuppliersRoute
  '/_authenticated/app/support': typeof AuthenticatedAppSupportRoute
  '/_authenticated/app/team': typeof AuthenticatedAppTeamRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/platform/admins': typeof AuthenticatedAppPlatformAdminsRoute
  '/_authenticated/app/platform/companies': typeof AuthenticatedAppPlatformCompaniesRoute
  '/_authenticated/app/platform/errors': typeof AuthenticatedAppPlatformErrorsRoute
  '/_authenticated/app/platform/releases': typeof AuthenticatedAppPlatformReleasesRoute
  '/_authenticated/app/platform/tickets': typeof AuthenticatedAppPlatformTicketsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/app'
    | '/onboarding'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/app/assist'
    | '/app/changelog'
    | '/app/customers'
    | '/app/debtors'
    | '/app/employees'
    | '/app/invoices'
    | '/app/payables'
    | '/app/pos'
    | '/app/products'
    | '/app/reminders'
    | '/app/settings'
    | '/app/suppliers'
    | '/app/support'
    | '/app/team'
    | '/app/'
    | '/app/platform/admins'
    | '/app/platform/companies'
    | '/app/platform/errors'
    | '/app/platform/releases'
    | '/app/platform/tickets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/onboarding'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/app/assist'
    | '/app/changelog'
    | '/app/customers'
    | '/app/debtors'
    | '/app/employees'
    | '/app/invoices'
    | '/app/payables'
    | '/app/pos'
    | '/app/products'
    | '/app/reminders'
    | '/app/settings'
    | '/app/suppliers'
    | '/app/support'
    | '/app/team'
    | '/app'
    | '/app/platform/admins'
    | '/app/platform/companies'
    | '/app/platform/errors'
    | '/app/platform/releases'
    | '/app/platform/tickets'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/app'
    | '/_authenticated/onboarding'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/app/assist'
    | '/_authenticated/app/changelog'
    | '/_authenticated/app/customers'
    | '/_authenticated/app/debtors'
    | '/_authenticated/app/employees'
    | '/_authenticated/app/invoices'
    | '/_authenticated/app/payables'
    | '/_authenticated/app/pos'
    | '/_authenticated/app/products'
    | '/_authenticated/app/reminders'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/suppliers'
    | '/_authenticated/app/support'
    | '/_authenticated/app/team'
    | '/_authenticated/app/'
    | '/_authenticated/app/platform/admins'
    | '/_authenticated/app/platform/companies'
    | '/_authenticated/app/platform/errors'
    | '/_authenticated/app/platform/releases'
    | '/_authenticated/app/platform/tickets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/team': {
      id: '/_authenticated/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AuthenticatedAppTeamRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/support': {
      id: '/_authenticated/app/support'
      path: '/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof AuthenticatedAppSupportRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/suppliers': {
      id: '/_authenticated/app/suppliers'
      path: '/suppliers'
      fullPath: '/app/suppliers'
      preLoaderRoute: typeof AuthenticatedAppSuppliersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/reminders': {
      id: '/_authenticated/app/reminders'
      path: '/reminders'
      fullPath: '/app/reminders'
      preLoaderRoute: typeof AuthenticatedAppRemindersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/products': {
      id: '/_authenticated/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AuthenticatedAppProductsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/pos': {
      id: '/_authenticated/app/pos'
      path: '/pos'
      fullPath: '/app/pos'
      preLoaderRoute: typeof AuthenticatedAppPosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/payables': {
      id: '/_authenticated/app/payables'
      path: '/payables'
      fullPath: '/app/payables'
      preLoaderRoute: typeof AuthenticatedAppPayablesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/invoices': {
      id: '/_authenticated/app/invoices'
      path: '/invoices'
      fullPath: '/app/invoices'
      preLoaderRoute: typeof AuthenticatedAppInvoicesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/employees': {
      id: '/_authenticated/app/employees'
      path: '/employees'
      fullPath: '/app/employees'
      preLoaderRoute: typeof AuthenticatedAppEmployeesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/debtors': {
      id: '/_authenticated/app/debtors'
      path: '/debtors'
      fullPath: '/app/debtors'
      preLoaderRoute: typeof AuthenticatedAppDebtorsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/customers': {
      id: '/_authenticated/app/customers'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AuthenticatedAppCustomersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/changelog': {
      id: '/_authenticated/app/changelog'
      path: '/changelog'
      fullPath: '/app/changelog'
      preLoaderRoute: typeof AuthenticatedAppChangelogRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/assist': {
      id: '/_authenticated/app/assist'
      path: '/assist'
      fullPath: '/app/assist'
      preLoaderRoute: typeof AuthenticatedAppAssistRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/platform/tickets': {
      id: '/_authenticated/app/platform/tickets'
      path: '/platform/tickets'
      fullPath: '/app/platform/tickets'
      preLoaderRoute: typeof AuthenticatedAppPlatformTicketsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/platform/releases': {
      id: '/_authenticated/app/platform/releases'
      path: '/platform/releases'
      fullPath: '/app/platform/releases'
      preLoaderRoute: typeof AuthenticatedAppPlatformReleasesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/platform/errors': {
      id: '/_authenticated/app/platform/errors'
      path: '/platform/errors'
      fullPath: '/app/platform/errors'
      preLoaderRoute: typeof AuthenticatedAppPlatformErrorsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/platform/companies': {
      id: '/_authenticated/app/platform/companies'
      path: '/platform/companies'
      fullPath: '/app/platform/companies'
      preLoaderRoute: typeof AuthenticatedAppPlatformCompaniesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/platform/admins': {
      id: '/_authenticated/app/platform/admins'
      path: '/platform/admins'
      fullPath: '/app/platform/admins'
      preLoaderRoute: typeof AuthenticatedAppPlatformAdminsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAssistRoute: typeof AuthenticatedAppAssistRoute
  AuthenticatedAppChangelogRoute: typeof AuthenticatedAppChangelogRoute
  AuthenticatedAppCustomersRoute: typeof AuthenticatedAppCustomersRoute
  AuthenticatedAppDebtorsRoute: typeof AuthenticatedAppDebtorsRoute
  AuthenticatedAppEmployeesRoute: typeof AuthenticatedAppEmployeesRoute
  AuthenticatedAppInvoicesRoute: typeof AuthenticatedAppInvoicesRoute
  AuthenticatedAppPayablesRoute: typeof AuthenticatedAppPayablesRoute
  AuthenticatedAppPosRoute: typeof AuthenticatedAppPosRoute
  AuthenticatedAppProductsRoute: typeof AuthenticatedAppProductsRoute
  AuthenticatedAppRemindersRoute: typeof AuthenticatedAppRemindersRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppSuppliersRoute: typeof AuthenticatedAppSuppliersRoute
  AuthenticatedAppSupportRoute: typeof AuthenticatedAppSupportRoute
  AuthenticatedAppTeamRoute: typeof AuthenticatedAppTeamRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppPlatformAdminsRoute: typeof AuthenticatedAppPlatformAdminsRoute
  AuthenticatedAppPlatformCompaniesRoute: typeof AuthenticatedAppPlatformCompaniesRoute
  AuthenticatedAppPlatformErrorsRoute: typeof AuthenticatedAppPlatformErrorsRoute
  AuthenticatedAppPlatformReleasesRoute: typeof AuthenticatedAppPlatformReleasesRoute
  AuthenticatedAppPlatformTicketsRoute: typeof AuthenticatedAppPlatformTicketsRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAssistRoute: AuthenticatedAppAssistRoute,
  AuthenticatedAppChangelogRoute: AuthenticatedAppChangelogRoute,
  AuthenticatedAppCustomersRoute: AuthenticatedAppCustomersRoute,
  AuthenticatedAppDebtorsRoute: AuthenticatedAppDebtorsRoute,
  AuthenticatedAppEmployeesRoute: AuthenticatedAppEmployeesRoute,
  AuthenticatedAppInvoicesRoute: AuthenticatedAppInvoicesRoute,
  AuthenticatedAppPayablesRoute: AuthenticatedAppPayablesRoute,
  AuthenticatedAppPosRoute: AuthenticatedAppPosRoute,
  AuthenticatedAppProductsRoute: AuthenticatedAppProductsRoute,
  AuthenticatedAppRemindersRoute: AuthenticatedAppRemindersRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppSuppliersRoute: AuthenticatedAppSuppliersRoute,
  AuthenticatedAppSupportRoute: AuthenticatedAppSupportRoute,
  AuthenticatedAppTeamRoute: AuthenticatedAppTeamRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppPlatformAdminsRoute: AuthenticatedAppPlatformAdminsRoute,
  AuthenticatedAppPlatformCompaniesRoute:
    AuthenticatedAppPlatformCompaniesRoute,
  AuthenticatedAppPlatformErrorsRoute: AuthenticatedAppPlatformErrorsRoute,
  AuthenticatedAppPlatformReleasesRoute: AuthenticatedAppPlatformReleasesRoute,
  AuthenticatedAppPlatformTicketsRoute: AuthenticatedAppPlatformTicketsRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
